language: node_js
node_js:
  - "stable"
branches:
  only:
    - master
cache:
  directories:
    - node_modules
    - ~/.npm
    - ~/.cache
  override:
    - npm ci
    - npm run cy:verify
before_script:
  - npm run lint
script:
  - npm run test:unit
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist
